### ISSUE TITLE
Save manager won't import the save file in 1.62

### ISSUE THREAD

**Issue by Orikario** [Ariescyn/EldenRing-Save-Manager#24]
The save file is able to be selected but once 'done' is clicked it stays in a clicked position but will not actually import the file with the name
![image](https://user-images.githubusercontent.com/75096822/199585233-164f5b6f-b70f-4cfd-85e5-7f5c3155dea3.png)

**Comment by Ariescyn** [comment]
It appears to be an unhandled error. 
What version of the app? 
Which OS? 
Are you on seamless co-op mode? 
Are you trying to import a save file from a different hard drive?
Is the file you're trying to import in a directory where the Save manager might not have privileges to access it?

I would like to reproduce this error on my end so any other information is appreciated

**Comment by Orikario** [comment]
- Tried it on previous versions, also didn't work
- Seamless coop mode was on
- Windows 10 (Don't know what version exactly I'll get it soon)
- Importing from my C drive where I have save data and the save manager
- Save manager should have permission to access the folder
- The save manager worked before but now it doesn't pretty sure I used 1.6 and it worked great 

**Note**: I used the update exe and that seemed to keep crashing on 1.6 meaning it wouldn't update. 
_That's all I can remember I'll answer any other questions to the best of my ability._

**Comment by Ariescyn** [comment]
Thanks for the reply
Even when downloading a fresh copy of v1.62 and trying to import the file, it fails? 
Does importing fail for any save file or just one?

I would definitely try a fresh copy of the save manager. If that doesn't work and you think it might be related to your particular save file, send me your save to scyntacks94@gmail.com

**Comment by Orikario** [comment]
I tried using a fresh copy of 1.62 and still didn't work
I tried using a different save also didn't work
Also found out I can't create saves on the manager.
I'll send my save file over so that you can see if it works for you. Honestly I think my OS might be messed up or something and that might be the cause but thats all I can think of.

**Comment by Ariescyn** [comment]
Well i just tried importing your save on 3 different PCs and it worked fine.. 
You could try to use it on a different Windows user or running as administrator?
Still seems like its a permissions issue on your system preventing the manager from accessing files

**Comment by Ariescyn** [comment]
Traceback (most recent call last):
  File "SaveManager.py", line 114, in archive_file
PermissionError: [Errno 13] Permission denied: './data/archive/TestSaveBackup__2022-11-22__(01.52.29)/info.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "SaveManager.py", line 401, in create_save
  File "SaveManager.py", line 127, in archive_file
PermissionError: [Errno 13] Permission denied: './data/archive/TestSaveBackup__2022-11-22__(01.52.29)/info.txt'
